image_width: 1440
image_height: 1080
camera_name: hk_left
camera_matrix:
  rows: 3
  cols: 3
  data: [1797.89325,    0.     ,  758.81394,
            0.     , 1798.80742,  558.09356,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.071930, 0.075803, 0.000314, -0.000094, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1779.07263,    0.     ,  758.8137 ,    0.     ,
            0.     , 1786.38   ,  557.92741,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
