image_width: 1440
image_height: 1080
camera_name: hk_right
camera_matrix:
  rows: 3
  cols: 3
  data: [1781.74415,    0.     ,  721.01267,
            0.     , 1781.80511,  520.28177,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.070227, 0.073725, -0.000842, -0.000318, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1763.28357,    0.     ,  720.24009,    0.     ,
            0.     , 1769.53247,  519.16789,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
